version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGODB_URI=mongodb+srv://calikm1975:Mustafa09@word-game-db.r2nlxja.mongodb.net/wordgame?retryWrites=true&w=majority&appName=word-game-db
      - REDIS_URL=redis://redis:6379

  frontend:
    build: ./frontend2025
    container_name: frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend

volumes:
  mongo-data:
